function [Ventilation, Outputs, VDPTable, MetricsTable] = Ventilation_Analysis_RH(Ventilation, Proton, MainInput)
%VENTILATION_ANALYSIS_RH Parallel multi-method VDP analysis entry point.
%RH edit: This entire RH-named file is a new, non-legacy entry point; the
% original Ventilation_Analysis.m remains unmodified.
%
% This is an RH-only entry point.  It deliberately leaves
% Ventilation_Analysis.m and all legacy VDP calculators unchanged.  It first
% uses the legacy function for shared image preparation (SNR, N4, VHI, masks,
% and standard NIfTI exports), with its legacy VDP/report branches disabled.
% It then runs the selected VDP methods through calculateAllVDPMethods_RH.
%
% The caller may select methods with the existing flags:
%   ThreshAnalysis, Kmeans, AKmeans, LB_Analysis
% and, for a subset of linear-binning methods:
%   Ventilation.LB_Methods = {'LBmean','GLBmean','HybridLBm','GLBpercentile'};
%
% If LB_Analysis is 'yes' and LB_Methods is not supplied, all four supported
% linear-binning methods are run.  This makes the RH pipeline usable from the
% existing app before its UI is updated with individual LB checkboxes.

    requiredMethods = {'LBmean','GLBmean','HybridLBm','GLBpercentile'};
    %RH edit: Accept an arbitrary selected subset of the four LB methods.
    Ventilation = iNormaliseLBMethods(Ventilation, requiredMethods);

    %RH edit: Ventilation_Analysis.m applies this exact same default
    % internally, but only returns Ventilation - not MainInput - so that
    % default never reaches the caller. Re-applying it here (identically)
    % ensures MainInput.ImageQuality/Note exist before calculateAllVDPMethods_RH
    % passes MainInput into ThresholdVDP_Report/LBVDP_Report/KmeansVDP_Report/
    % AKmeansVDP_Report, all of which read those fields directly.
    if ~isfield(MainInput, 'ImageQuality') || isempty(MainInput.ImageQuality)
        MainInput.ImageQuality = '';
    end
    if ~isfield(MainInput, 'Note') || isempty(MainInput.Note)
        MainInput.Note = '';
    end

    %RH edit: Preserve the requested analysis choices.  The legacy entry point below
    % must only do its shared preprocessing; otherwise it would calculate and
    % report the selected VDP methods a second time.
    requested = Ventilation;
    prepInput = Ventilation;
    prepInput.ThreshAnalysis = 'no';
    prepInput.LB_Analysis = 'no';
    prepInput.Kmeans = 'no';
    prepInput.AKmeans = 'no';
    prepInput.DDI2D = 'no';
    prepInput.DDI3D = 'no';
    prepInput.GLRLM_Analysis = 'no';
    prepInput.writereport = 'no';

    %RH edit: Run legacy shared preprocessing only; RH coordinates all VDP methods.
    Ventilation = VentilationFunctions.Ventilation_Analysis( ...
        prepInput, Proton, MainInput);

    % Restore the user's selections after preprocessing.  Values generated by
    % preprocessing remain in Ventilation, while these fields control the RH
    % coordinator.
    selectionFields = {'ThreshAnalysis','LB_Analysis','LB_Methods', ...
        'Kmeans','AKmeans','DDI2D','DDI3D','GLRLM_Analysis'};
    for k = 1:numel(selectionFields)
        fieldName = selectionFields{k};
        if isfield(requested, fieldName)
            Ventilation.(fieldName) = requested.(fieldName);
        end
    end

    %RH edit: The RH coordinator now runs DDI/GLRLM using their selected map.
    subjectID = iSubjectID(MainInput);
    [Ventilation, Outputs, VDPTable, MetricsTable] = ...
        VentilationFunctions.calculateAllVDPMethods_RH( ...
        Ventilation, Proton, MainInput, subjectID);

    %RH edit: Keep all multi-method results attached to Ventilation without
    % disturbing legacy result-field conventions.
    Ventilation.RHOutputs = Outputs;
    Ventilation.RHVDPSummary = VDPTable;
    Ventilation.RHMethodMetrics = MetricsTable;

    %RH edit: Overwrite the single Ventilation_Analysis.mat that the shared
    % prep step (VentilationFunctions.Ventilation_Analysis) already wrote,
    % now with the complete post-multi-method data. Only one .mat file should
    % exist per subject - no separate "_RH" workspace file.
    workspaceFile = fullfile(Ventilation.parentPath, ...
        'Ventilation_Analysis.mat');
    save(workspaceFile, 'Ventilation', 'Proton', 'MainInput', ...
        'Outputs', 'VDPTable', 'MetricsTable', '-v7.3');
end

function Ventilation = iNormaliseLBMethods(Ventilation, allowedMethods)
    if ~isfield(Ventilation, 'LB_Analysis') || ...
            ~iIsYes(Ventilation.LB_Analysis)
        Ventilation.LB_Methods = {};
        return
    end

    if ~isfield(Ventilation, 'LB_Methods') || isempty(Ventilation.LB_Methods)
        %RH edit: Compatibility default for the current one-checkbox App UI.
        Ventilation.LB_Methods = allowedMethods;
        return
    end

    methods = cellstr(string(Ventilation.LB_Methods));
    methods = methods(ismember(methods, allowedMethods));
    Ventilation.LB_Methods = unique(methods, 'stable');

    if isempty(Ventilation.LB_Methods)
        error('VentilationFunctions:RHNoValidLBMethod', ...
            'LB_Methods did not contain an RH-supported linear-binning method.');
    end
end

function subjectID = iSubjectID(MainInput)
    candidates = {'SubjectID','SUBJECTID','Subject','PatientID','SCAN_NUM'};
    subjectID = "UnknownSubject";
    for k = 1:numel(candidates)
        name = candidates{k};
        if isfield(MainInput, name) && ~isempty(MainInput.(name))
            subjectID = string(MainInput.(name));
            return
        end
    end
end

function tf = iIsYes(value)
    if islogical(value) || isnumeric(value)
        tf = logical(value);
    else
        tf = strcmpi(strtrim(string(value)), "yes");
    end
end
